version: "3"
services:
  client:
    build:
      context: ./client
    expose:
      - "3000"
    ports:
      - "4001:3000"
  server:
    build:
      context: ./server
    expose:
      - "5000"
    ports:
      - "4002:5000"
